before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: hrv-darwin
  binary: hrv
  main: ./cmd/hrv/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/harvest.version={{.Version}} -X github.com/k1LoW/harvest.commit={{.FullCommit}} -X github.com/k1LoW/harvest.date={{.Date}} -X github.com/k1LoW/harvest/version.Version={{.Version}}
  env:
    - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
-
  id: hrv-linux
  binary: hrv
  main: ./cmd/hrv/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/harvest.version={{.Version}} -X github.com/k1LoW/harvest.commit={{.FullCommit}} -X github.com/k1LoW/harvest.date={{.Date}} -X github.com/k1LoW/harvest/version.Version={{.Version}}
    - -linkmode external
    - -extldflags "-static"
  env:
    - CGO_ENABLED=1
    - CC=/usr/local/bin/x86_64-linux-musl-cc
  goos:
    - linux
  goarch:
    - amd64
archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  name: harvest
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/harvest
  description: 'Portable log aggregation tool for middle-scale system operation/observation.'
  install: bin.install 'hrv'
