language: go
matrix:
  include:
  - go: 1.11.x
    env: GO111MODULE=on RELEASE_BUILD=true
  - go: 1.12.x
    env: GO111MODULE=on
  - go: master
    env: GO111MODULE=on
install:
  - echo $TRAVIS_GO_VERSION
  - make depsdev
script:
  - make ci
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $RELEASE_BUILD = true
